name: Build & Push to DockerHub
on: push
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm windows-spotlight
